apps/hygiene/urls.py
from django.urls import re_path as url

from apps.hygiene import views

app_name = 'hygiene'

urlpatterns = [
    url('^check/$', views.check, name='check'),
    url('^check/(?P<pk>[0-9]+)/$', views.check, name='check_day'),

    url('^plan/$', views.plan, name='plan'),
    url('^plan/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', views.plan, name='plan_month'),

    url('^calendar/(?P<pk>[0-9]+).ics', views.ical, name='ical'),
]

urls.py
from django.conf import settings
from django.urls import re_path as url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^multivers/', include('apps.multivers.urls')),
    url(r'^grolsch/', include('apps.grolsch.urls')),
    url(r'^mail/', include('apps.mail.urls')),
    url(r'^flow/', include('apps.flowguard.urls')),
    url(r'^hygiene/', include('apps.hygiene.urls')),
    url(r'^', include('apps.general.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/hygiene/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class CheckDay(models.Model):
    date = models.DateField()
    checker = models.ForeignKey("auth.User", models.PROTECT)
    comments = models.TextField(blank=True)

    def __str__(self):
        return self.date.strftime("%Y-%m-%d")


class CheckLocation(models.Model):
    name = models.CharField(max_length=255)

    @property
    def shorthand(self):
        return self.name[:2]

    def __str__(self):
        return self.name


class CheckItem(models.Model):
    name = models.CharField(max_length=255)
    location = models.ForeignKey("hygiene.CheckLocation", models.CASCADE)

    def __str__(self):
        return "{} @ {}".format(self.name, self.location)


class CheckDayItem(models.Model):
    RESULT_CHOICES = [
        ('GOOD', _('✓')),
        ('ACCEPT', _('~')),
        ('BAD', _('✗')),
    ]

    item = models.ForeignKey("hygiene.CheckItem", models.CASCADE)
    day = models.ForeignKey("hygiene.CheckDay", on_delete=models.CASCADE)
    result = models.CharField(max_length=8, choices=RESULT_CHOICES)

apps/hygiene/forms.py
from django import forms
from django.contrib.auth.models import User

from apps.hygiene.models import CheckDay, CheckDayItem, CheckItem


class CheckDayForm(forms.ModelForm):
    date = forms.DateField(widget=forms.HiddenInput())
    checker = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True), required=False)

    def __init__(self, *args, **kwargs):
        self.declared_fields['checker'].label_from_instance = lambda obj: obj.get_full_name()
        super(CheckDayForm, self).__init__(*args, **kwargs)

    class Meta:
        fields = ['date', 'checker']
        model = CheckDay


class CheckDayCommentsForm(forms.ModelForm):
    class Meta:
        fields = ['comments']
        model = CheckDay


class CheckDayItemForm(forms.ModelForm):
    class Meta:
        model = CheckDayItem
        fields = ['result']

apps/hygiene/views.py
import calendar
from collections import defaultdict

import icalendar

import datetime

import pytz
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from apps.hygiene.forms import CheckDayForm, CheckDayItemForm, CheckDayCommentsForm
from apps.hygiene.models import CheckDay, CheckItem, CheckDayItem, CheckLocation


@login_required
def check(request, pk=None):
    today = datetime.date.today()
    post_data = request.POST if request.method == 'POST' else None

    obj = CheckDay.objects.filter(date=today).first() if pk is None else get_object_or_404(CheckDay, pk=pk)
    check_date = obj.date if obj is not None else today
    obj_form = CheckDayCommentsForm(instance=obj, data=post_data)

    if request.method == 'POST':
        if obj_form.is_valid():
            obj = obj_form.save(commit=False)
            if obj.date is None:
                obj.date = check_date
            if obj.checker_id is None or obj.checker != request.user:
                obj.checker = request.user
            obj.save()

    items = CheckDayItem.objects.filter(day=obj)
    items = {item.item.pk: item for item in items}

    all_good = obj is not None

    locations = CheckLocation.objects.all()

    for location in locations:
        location.items = CheckItem.objects.filter(location=location).all()
        for item in location.items:
            instance = items.get(item.pk, None)
            data = post_data
            initial_result = data.get(str(item.pk) + '-result', None) if data else None
            if instance and initial_result is None: initial_result = instance.result
            initial = {'result': initial_result}
            item.form = CheckDayItemForm(prefix=item.pk, instance=instance, data=data, initial=initial)

            if request.method == 'POST' and obj is not None:
                if item.form.is_valid():
                    checked_item = item.form.save(commit=False)
                    checked_item.day = obj
                    checked_item.item = item
                    checked_item.save()
                else:
                    all_good = False

    if request.method == 'POST' and all_good:
        return redirect('hygiene:check_day', obj.pk)

    return render(request, 'hygiene/check.html', locals())


@login_required
def plan(request, year=None, month=None):
    now = timezone.now()
    year = now.year if year is None else int(year)
    month = now.month if month is None else int(month)
    start_date = datetime.date(year, month, 1)

    prev_month = (month - 2) % 12 + 1
    next_month = month % 12 + 1
    prev_year = year - (month == 1)
    next_year = year + (month == 12)

    cal = calendar.Calendar(calendar.MONDAY)
    dates = list(cal.itermonthdates(year, month))
    weeks_dates = [dates[i*7:(i+1)*7] for i in range(len(dates) // 7)]

    check_days = CheckDay.objects.filter(date__gte=dates[0], date__lte=dates[-1]).prefetch_related('checkdayitem_set')
    check_days = {check_day.date: check_day for check_day in check_days}

    weeks = []

    for week_dates in weeks_dates:
        week = []

        for date in week_dates:
            instance = check_days.get(date, None)
            data = request.POST if request.method == 'POST' else None
            form = CheckDayForm(prefix=date.strftime("%Y%m%d"), instance=instance, data=data, initial={'date': date, 'checker': instance.checker.pk if instance else None})

            points = defaultdict(list)

            if instance:
                for item in instance.checkdayitem_set.all():
                    points[item.item.location].append({
                        'GOOD': 'A', 'ACCEPT': 'B', 'BAD': 'C'
                    }[item.result])

                for location in points.keys():
                    results = list(sorted(points[location]))
                    result_many = results[len(results)*3//4]
                    result_few = results[len(results)*7//8]
                    result = {'AA': 'A', 'AB': 'A', 'AC': 'B', 'BB': 'B', 'BC': 'C', 'CC': 'C'}
                    points[location] = result[result_many + result_few]

            if request.method == 'POST' and form.is_valid():
                if form.cleaned_data['checker'] is None:
                    if instance is not None:
                        instance.delete()
                else:
                    form.save()

            week.append((form, dict(points)))

        weeks.append(week)

    if request.method == 'POST':
        return redirect('hygiene:plan')

    return render(request, 'hygiene/plan.html', locals())


def ical(request, pk):
    user = get_object_or_404(User, pk=pk)
    days = CheckDay.objects.filter(checker=user).all()
    sbz_location = pytz.timezone('Europe/Amsterdam')

    cal = icalendar.Calendar()

    for day in days:
        event = icalendar.Event()
        event['uid'] = day.pk
        event.add('dtstart', sbz_location.localize(datetime.datetime.combine(day.date, datetime.time(8, 30))).astimezone(pytz.UTC))
        event.add('dtend', sbz_location.localize(datetime.datetime.combine(day.date, datetime.time(9, 0))).astimezone(pytz.UTC))
        event.add('summary', 'Check Drink Rooms')
        # event.add('description', reverse_lazy('hygiene:check_day', day.pk))
        cal.add_component(event)

    return HttpResponse(cal.to_ical(), content_type='text/calendar')

apps/hygiene/templates/hygiene/check.html
{% extends 'base.html' %}

{% load i18n bootstrap_form %}

{% block title %}SBZ -- Hygiene Check{% endblock %}

{% block content %}
    <h1>{{ check_date }}</h1>

    {% if obj.checker != user %}
        <div class="alert alert-warning" role="alert">
            You are not assigned to check today, you will be assigned automatically on save.
        </div>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        {% for location in locations %}
            <h2>{{ location }}</h2>
            {% for item in location.items %}
                {{ item.form.result.errors|bootstrap_form_errors }}
                <p>
                    <div class="btn-group btn-group-toggle" data-toggle="buttons">
                        {% for option in item.form.result.field.choices %}
                            {% if option.0 != '' %}
                                <label class="btn btn-outline-secondary {% if item.form.result.initial == option.0 %}active{% endif %}">
                                    <input type="radio" name="{{ item.form.result.html_name }}" value="{{ option.0 }}" {% if item.form.result.initial == option.0 %}checked{% endif %}>
                                    {{ option.1 }}
                                </label>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <label style="margin-left: 1ch">{{ item.name }}</label>
                </p>
            {% endfor %}
        {% endfor %}

        {{ obj_form|bootstrap_form }}

        <input type="submit" value="Save" class="btn btn-primary">
    </form>
{% endblock %}

apps/hygiene/templates/hygiene/plan.html
{% extends 'base.html' %}

{% load i18n bootstrap_form %}

{% block title %}SBZ -- Hygiene Check Planning{% endblock %}

{% block content %}
    <h1>
        <a href="{% url "hygiene:plan_month" prev_year prev_month %}" class="btn btn-secondary">‹</a>
        {{ start_date|date:"F Y"|capfirst }}
        <a href="{% url "hygiene:plan_month" next_year next_month %}" class="btn btn-secondary">›</a>
    </h1>
    <a href="{% url 'hygiene:ical' user.pk %}">Your calendar (.ics)</a>
    <form action="" method="POST">
        {% csrf_token %}
        <table class="table table-sm-rows">
            {% for week in weeks %}
                <tr>
                    {% for form, locations in week %}
                        <td>
                            {% if form.instance.pk %}
                                <a href="{% url 'hygiene:check_day' form.instance.pk %}">
                                    <h4 class="no-margin {% if form.date.initial.year != year or form.date.initial.month != month %}faded{% endif %}">{{ form.date.initial|date:"D j" }}</h4>
                                </a>
                            {% else %}
                                <h4 class="no-margin {% if form.date.initial.year != year or form.date.initial.month != month %}faded{% endif %}">{{ form.date.initial|date:"D j" }}</h4>
                            {% endif %}

                            <div class="location-status-container">
                                {% for location, points in locations.items %}
                                    <span class="location-status location-status-{{ points }}">
                                        {{ location.shorthand }}
                                    </span>
                                {% endfor %}
                            </div>

                            {{ form.date }}
                            <div class="form-group">
                                {{ form.checker.errors|bootstrap_form_errors }}
                                <select name="{{ form.checker.html_name }}" id="{{ form.checker.id_for_label }}" class="form-control">
                                    {% for option in form.checker.field.choices %}
                                        <option value="{{ option.0 }}"
                                                {% if form.checker.initial == option.0 %}selected{% endif %}>{{ option.1 }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>

        <input type="submit" value="Save" class="btn btn-primary">
    </form>
{% endblock %}