apps/flowguard/urls.py
from django.urls import re_path as url

from apps.flowguard import views

app_name = 'flowguard'

urlpatterns = [
    url(r'api/1/update$', views.update, name='update'),
    url(r'monitor/$', views.monitor, name='monitor'),
    # url(r'stats/$', views.stats, name='stats'),
    # url(r'lookup/$', views.lookup, name='lookup'),
    url(r'history/$', views.history, name='history'),
    url(r'history/(?P<year>[0-9]+)/(?P<month>[0-9]+)$', views.history, name='history_month'),
]

urls.py
from django.conf import settings
from django.urls import re_path as url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^multivers/', include('apps.multivers.urls')),
    url(r'^grolsch/', include('apps.grolsch.urls')),
    url(r'^mail/', include('apps.mail.urls')),
    url(r'^flow/', include('apps.flowguard.urls')),
    url(r'^hygiene/', include('apps.hygiene.urls')),
    url(r'^', include('apps.general.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/flowguard/models.py
from django.db import models


class FlowValue(models.Model):
    channel = models.ForeignKey("flowguard.FlowChannel", on_delete=models.CASCADE)
    value = models.DecimalField(decimal_places=1, max_digits=10)
    first_seen = models.DateTimeField()
    last_seen = models.DateTimeField()

    def __str__(self):
        return "Value of {} between {} and {}: {}".format(self.channel, self.first_seen, self.last_seen, self.value)


class FlowChannel(models.Model):
    index = models.PositiveIntegerField()
    name = models.CharField(max_length=255)

    def __str__(self):
        return "{} (Index {})".format(self.name, self.index)

apps/flowguard/views.py
import calendar
import json
import logging
from datetime import timedelta, datetime, time

from decimal import Decimal

import pytz
from socketIO_client import SocketIO, BaseNamespace
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.db.models import Max
from django.http import HttpResponseBadRequest, HttpResponse, Http404
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

@csrf_exempt
@require_POST
def update(request):
    if request.POST.get('secret', '') != settings.UPDATE_FLOW_SECRET:
        raise PermissionDenied

    now = timezone.now()
    updates = []

    try:
        data = json.loads(request.POST.get('data', ''))
        for value in data:
            update = {}
            channel = FlowChannel.objects.get(index=int(value['index']))
            update['channel_id'] = channel.pk
            update['channel_name'] = channel.name
            last_value = FlowValue.objects.filter(channel=channel).order_by('-last_seen').first()
            last_int_value = int(last_value.value * 10) # Decimal object, so this is exact.
            last_raw_value = last_int_value % (2**16)
            last_value_wraps = last_int_value // (2**16)

            if last_raw_value == value['value']:
                value = last_value
                value.last_seen = now
            else:
                # If the flowmeter powers down, it might round down a bit, so allow 10L of backward flow.
                if value['value'] < last_raw_value - 100:
                    wraps = last_value_wraps + 1
                    raw = value['value']
                else:
                    wraps = last_value_wraps
                    raw = value['value']

                value = FlowValue(channel=channel, value=(Decimal(wraps*2**16 + raw) / Decimal(10)), first_seen=now, last_seen=now)

            value.save()
            update['value'] = float(value.value)
            update['first_seen'] = value.first_seen.isoformat()
            update['last_seen'] = value.last_seen.isoformat()
            updates.append(update)
    except (json.JSONDecodeError, ValueError, TypeError):
        return HttpResponseBadRequest()

    # new_values = FlowValue.objects.values('channel').annotate(max_date=Max('last_seen'))

    #with SocketIO(settings.FULL_LIVE_URL_HOST, settings.FULL_LIVE_URL_PORT, BaseNamespace) as bare_socket:
    #    socket = bare_socket.define(BaseNamespace, '/sbz/flow')
    #    socket.emit('update_flow', {'secret': settings.UPDATE_FLOW_SECRET, 'data': updates})

    return HttpResponse()


from apps.flowguard.models import FlowChannel, FlowValue


def monitor(request):
    socketio_url = "https://sbz.utwente.nl"
    channels = FlowChannel.objects.all()
    use_dark_theme = True
    for channel in channels:
        channel.value = FlowValue.objects.filter(channel=channel).order_by("-last_seen").first()
    return render(request, 'flow/monitor.html', locals())


def stats(request):
    return None


def lookup(request):
    return None


def history(request, year=None, month=None):
    class data: pass
    now = timezone.now()

    year = now.year if year is None else int(year)
    month = now.month if month is None else int(month)

    if not (2000 <= year < 2100) or not (1 <= month <= 12):
        raise Http404

    prev_month = (month - 2) % 12 + 1
    next_month = month % 12 + 1
    prev_year = year - (month == 1)
    next_year = year + (month == 12)

    sbz_location = pytz.timezone('Europe/Amsterdam')
    start_date = sbz_location.localize(datetime(year, month, 1))

    cal = calendar.Calendar(calendar.MONDAY)
    dates = list(cal.itermonthdates(year, month))
    assert len(dates) % 7 == 0

    channels = FlowChannel.objects.all()
    channel_values = []

    for channel in channels:
        start = sbz_location.localize(datetime.combine(dates[0], time()))
        end = sbz_location.localize(datetime.combine(dates[-1], time())) + timedelta(days=1)
        flow_values = FlowValue.objects.filter(channel=channel, last_seen__gte=start, first_seen__lt=end).order_by("first_seen").all()

        week_flows = []

        for week in range(len(dates)//7):
            week_flows.append([])
            for day in range(7):
                week_flows[week].append(data())
                week_flows[week][day].date = sbz_location.localize(datetime.combine(dates[week*7+day], time()))
                week_flows[week][day].hours = []
                for hour in range(24):
                    week_flows[week][day].hours.append(0.0)

        for fr, to in zip(flow_values, flow_values[1:]):
            midpoint = fr.last_seen + (to.first_seen - fr.last_seen) / 2
            midpoint = midpoint.astimezone(sbz_location)
            flow = float(to.value - fr.value)

            if midpoint.date() in dates:
                index = dates.index(midpoint.date())
                week_flows[index // 7][index % 7].hours[midpoint.hour] += flow

        datum = data()
        datum.flows = week_flows
        datum.channel = channel
        channel_values.append(datum)

    return render(request, 'flow/history.html', locals())

apps/flowguard/templates/flow/history.html
{% extends 'base.html' %}

{% load i18n flow %}

{% block title %}SBZ -- FlowGuard History{% endblock %}

{% block content %}
    <h1>
        <a href="{% url "flowguard:history_month" prev_year prev_month %}" class="btn btn-secondary">‹</a>
        {{ start_date|date:"F Y"|capfirst }}
        <a href="{% url "flowguard:history_month" next_year next_month %}" class="btn btn-secondary">›</a>
    </h1>
    <p>
        <div id="start">&nbsp;</div>
        <div id="end">&nbsp;</div>
        <div id="difference">Try dragging across the flow indicators</div>
    </p>
    {% for channel in channel_values %}
        <h2>

            {{ channel.channel.name }}

        </h2>
        <table class="table table-sm-rows">
            {% for week in channel.flows %}
                <tr>
                    {% for day in week %}
                        <td class="flow-history-td">
                            <h3 class="{% if day.date.year != year or day.date.month != month %}faded{% endif %}">{{ day.date|date:"D j" }}</h3>
                            <div class="flow-history-values">
                                {% for hour in day.hours %}<span class="flow-history-value" style="background-color: {{ hour.flow|flow_color }}"
                                                                 data-value='"{{ hour.flow|escapejs }}"'
                                                                 data-start-value='"{{ hour.start_value|escapejs }}"'
                                                                 data-end-value='"{{ hour.end_value|escapejs }}"'
                                                                 draggable="true"
                                                                 data-channel="{{ channel.channel.pk }}" data-date="{{ day.date|date:"D j F" }}" data-hour="{{ forloop.counter0 }}">

                                </span>{% endfor %}
                            </div>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    {% endfor %}

    <script type="text/javascript">
        let currentStart = null;

        function updateRange(start, end) {
            for(let node of document.querySelectorAll('.flow-history-value-select-start')) node.classList.remove('flow-history-value-select-start');
            for(let node of document.querySelectorAll('.flow-history-value-select-end')) node.classList.remove('flow-history-value-select-end');
            for(let node of document.querySelectorAll('.flow-history-value-select')) node.classList.remove('flow-history-value-select');

            if(start.dataset.channel !== end.dataset.channel) return '(invalid range)';

            let left = `${start.dataset.date} ${start.dataset.hour}:00`;
            let right = `${end.dataset.date} ${end.dataset.hour}:59`;
            document.querySelector('#start').textContent = `${left}: ${parseFloat(JSON.parse(start.dataset.startValue)).toFixed(1)}`;
            document.querySelector('#end').textContent = `${right}: ${parseFloat(JSON.parse(end.dataset.endValue)).toFixed(1)}`;

            let total = 0.0;
            let node = start;
            node.classList.add('flow-history-value-select-start');
            total += parseFloat(JSON.parse(node.dataset.value));

            while(node !== end) {
                if(node.nextElementSibling) {
                    node = node.nextElementSibling;
                } else if(node.parentNode.parentNode.nextElementSibling) {
                    node = node.parentNode.parentNode.nextElementSibling.querySelector('.flow-history-value');
                } else {
                    let nextTr = node.parentNode.parentNode.parentNode.nextElementSibling;

                    if(!nextTr) {
                        return updateRange(end, start);
                    }

                    node = nextTr.querySelector('.flow-history-value');
                }

                total += parseFloat(JSON.parse(node.dataset.value));
                if(node === end) break;

                node.classList.add('flow-history-value-select');
            }

            end.classList.add('flow-history-value-select-end');

            return `Difference: ${total.toFixed(1)}ℓ`;
        }

        function update(end) {
            let selectionText = updateRange(currentStart, end);
            document.querySelector('#difference').textContent = selectionText;
        }

        function onStart(e) {
            if(e.buttons & 1) {
                e.preventDefault();
                e.target.classList.add('flow-history-value-select-start');
                currentStart = e.target;
                update(e.target);
            }
        }

        function onEnd(e) {
            if(e.buttons & 1) {
                e.preventDefault();
                update(e.target);
            }
        }

        window.addEventListener('load', function() {
            for(const value of document.querySelectorAll('.flow-history-value')) {
                value.addEventListener('mousedown', onStart);
                value.addEventListener('mouseover', onEnd);
                value.addEventListener('mouseup', onEnd);
            }
        });
    </script>
{% endblock %}

apps/flowguard/templates/flow/monitor.html
{% load i18n static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>SBZ -- Monitor</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.3.1/slate/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/jquery.sparkline.min.js' %}"></script>
        <script src="{% static 'js/socket.io.js' %}"></script>
    </head>
    <body><div class="container">
        <script type="text/javascript">
            function formatDate(secs) {
                if(secs < 15*60) {
                    return 'Live';
                } else if(secs < 60 * 60) {
                    return Math.round(secs / 60) + 'm ago';
                } else if(secs < 60 * 60 * 24) {
                    return Math.round(secs / 60 / 60) + 'h ' + Math.round((secs / 60) % 60) + 'm ago';
                } else {
                    return Math.round(secs / 60 / 60 / 24) + 'd ago';
                }
            }

            function getStoredValue(channel) {
                if(localStorage[channel.channel_id] === undefined) {
                    localStorage[channel.channel_id] = channel.value + '';
                    return channel.value;
                } else {
                    return parseFloat(localStorage[channel.channel_id]);
                }
            }

            function reset(e, channel) {
                const root = document.querySelector('[data-channel-pk="' + channel + '"]');
                localStorage.removeItem(channel);
                root.querySelector('.data-diff').textContent = '0,0';
            }

            const socket = io('{{ socketio_url|escapejs }}/sbz/flow');
            var sparkline = {};
            var lastValue = {};

            socket.on('connect', function() {
                socket.on('flow', function(data) {
                    for(const channel of data) {
                        const root = document.querySelector('[data-channel-pk="' + channel.channel_id + '"]');
                        root.querySelector('.data-channel-name').textContent = channel.channel_name;
                        root.querySelector('.data-value').textContent = (channel.value.toFixed(1) + '').replace('.', ',');
                        const date = new Date(channel.first_seen);
                        const time = root.querySelector('.data-time');
                        time.dateTime = date.toISOString();
                        const secondDifference = ((new Date()).getTime() - date.getTime()) / 1000;
                        const dateText = formatDate(secondDifference);
                        time.textContent = dateText;
                        root.querySelector('.data-live').style.display = (dateText == 'Live') ? 'inline' : 'none';
                        const storedValue = getStoredValue(channel);
                        root.querySelector('.data-diff').textContent = (channel.value - storedValue).toFixed(1).replace('.', ',');

                        if(secondDifference > 30*60) {
                            root.querySelector('.data-sparkline').textContent = '';
                            lastValue[channel.channel_id] = undefined;
                            sparkline[channel.channel_id] = undefined;
                        } else if(lastValue[channel.channel_id] === undefined) {
                            lastValue[channel.channel_id] = channel.value;
                        } else {
                            if(sparkline[channel.channel_id] === undefined) {
                                sparkline[channel.channel_id] = [];
                            }

                            sparkline[channel.channel_id].push(channel.value - lastValue[channel.channel_id]);
                            lastValue[channel.channel_id] = channel.value;

                            if(sparkline[channel.channel_id].length > 60) {
                                sparkline[channel.channel_id].splice(0, 1);
                            }

                            $(root.querySelector('.data-sparkline')).sparkline(sparkline[channel.channel_id], {
                                width: '100%',
                                height: '40px',
                                disableTooltips: true,
                            });
                        }
                    }
                });
            });
        </script>

        <div class="row">
        {% for channel in channels %}
            <div class="col-md-6 my-2" data-channel-pk="{{ channel.pk }}">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <h1 class="data-channel-name">{{ channel.name }}</h1>
                            </div>
                            <div class="col">
                                <p class="text-right">
                                    <time class="data-time">...</time>
                                    <span class="data-live livedot"></span>
                                </p>
                            </div>
                        </div>
                        <h1 class="display-3">
                            <span class="data-value">{{ channel.value.value }}</span>
                            <small>ℓ</small>
                        </h1>
                        <div class="row">
                            <div class="col">
                                <h3 class="text-success">
                                    +
                                    <span class="data-diff">...</span>
                                    <small>ℓ</small>
                                    <button class="btn btn-sm btn-warning" type="button" onclick="reset(event, {{ channel.pk }})">
                                        Reset
                                    </button>
                                </h3>
                            </div>
                            <div class="col data-sparkline">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div></body>
</html>