apps/flowguard/urls.py
from django.urls import re_path as url

from apps.flowguard import views

app_name = 'flowguard'

urlpatterns = [
    url(r'api/1/update$', views.update, name='update'),
    url(r'monitor/$', views.monitor, name='monitor'),
    # url(r'stats/$', views.stats, name='stats'),
    # url(r'lookup/$', views.lookup, name='lookup'),
    url(r'history/$', views.history, name='history'),
    url(r'history/(?P<year>[0-9]+)/(?P<month>[0-9]+)$', views.history, name='history_month'),
]

apps/general/urls.py
from django.urls import re_path as url

from . import views

app_name = 'general'

urlpatterns = [
    url(r'^$', view=views.index, name='index'),
    url(r'^construction/', view=views.construction, name='construction'),
    url(r'^contact/', view=views.contact, name='contact'),

    url(r'^login$', view=views.login, name='login'),
    url(r'^logout$', view=views.logout, name='logout'),
]

apps/grolsch/urls.py
from django.urls import re_path as url
from . import views

app_name = 'grolsch'

urlpatterns = [
    url('^products$', views.ProductList.as_view(), name='products'),
    url('^product/create$', views.ProductCreate.as_view(), name='product_create'),
    url('^product/(?P<pk>[0-9]+)/delete$', views.ProductDelete.as_view(), name='product_delete'),

    url('^price_changes$', views.PriceChangeList.as_view(), name='price_changes'),
    url('^price_change/(?P<pk>[0-9]+)$', views.PriceChangeDetail.as_view(), name='price_change_detail'),
    url('^price_change/(?P<pk>[0-9]+)/resolve$', views.PriceChangeResolve.as_view(), name='price_change_resolve')
]

apps/hygiene/urls.py
from django.urls import re_path as url

from apps.hygiene import views

app_name = 'hygiene'

urlpatterns = [
    url('^check/$', views.check, name='check'),
    url('^check/(?P<pk>[0-9]+)/$', views.check, name='check_day'),

    url('^plan/$', views.plan, name='plan'),
    url('^plan/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', views.plan, name='plan_month'),

    url('^calendar/(?P<pk>[0-9]+).ics', views.ical, name='ical'),
]

urls.py
from django.conf import settings
from django.urls import re_path as url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^multivers/', include('apps.multivers.urls')),
    url(r'^grolsch/', include('apps.grolsch.urls')),
    url(r'^mail/', include('apps.mail.urls')),
    url(r'^flow/', include('apps.flowguard.urls')),
    url(r'^hygiene/', include('apps.hygiene.urls')),
    url(r'^', include('apps.general.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load i18n static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
</head>
<body>
<form id="logout" method="POST" action="{% url 'general:logout' %}" style="display: none">
    {% csrf_token %}
</form>

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <div class="container">
        <a class="navbar-brand" href="{% url 'general:index' %}"><img src=https://i.ibb.co/qN8kvSC/sbz-logo.png alt="sbz-beter" border="0"></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item {% if active_id == "home" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'general:index' %}">Home</a>
                </li>
                <li class="nav-item {% if active_id == "construction" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'general:construction' %}">Structure</a>
                </li>
                <li class="nav-item {% if active_id == "contact" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'general:contact' %}">Contact</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="dropdown {% if active_id == "multivers" %}active{% endif %}">
                        <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">
                            Multivers
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'multivers:products' %}" class="dropdown-item">Products</a>
                                <a href="{% url 'multivers:index' %}" class="dropdown-item">Sales</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown {% if active_id == "grolsch" %}active{% endif %}">
                        <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">
                            Grolsch
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'grolsch:products' %}" class="dropdown-item">Products</a>
                                <a href="{% url 'grolsch:price_changes' %}" class="dropdown-item">Price changes</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown {% if active_id == "flow" %}active{% endif %}">
                        <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">
                            FlowGuard
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'flowguard:monitor' %}" class="dropdown-item" target="_blank">
                                    Monitor
                                    <span class="oi oi-external-link float-right"></span>
                                </a>
                                <a href="{% url 'flowguard:history' %}" class="dropdown-item">History</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown {% if active_id == "hygiene" %}active{% endif %}">
                        <a href="" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">
                            Hygiene
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'hygiene:check' %}" class="dropdown-item">Check Today</a>
                                <a href="{% url 'hygiene:plan' %}" class="dropdown-item">Planning</a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown {% if messages %}show{% endif %}">
                    <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                        {% if user.is_authenticated %}
                            {{ user.first_name }}
                        {% else %}
                            Login
                        {% endif %}
                        <span class="caret"></span>
                    </a>
                    {% if user.is_authenticated %}
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                                <a class="dropdown-item" href="#" onclick="$('#logout').submit();">Logout</a>
                            </li>
                        </ul>
                    {% else %}
                        <div class="dropdown-menu dropdown-menu-right {% if messages %}show{% endif %}">
                            <form class="p-3" method="POST" action="{% url 'general:login' %}">
                                {% csrf_token %}
                                {% for message in messages %}
                                    <div class="alert alert-warning" role="alert">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input type="text" class="form-control" id="username" name="username" placeholder="username">
                                </div>
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control" id="password" name="password" placeholder="password">
                                </div>
                                <button type="submit" class="btn btn-primary">Login</button>
                            </form>
                        </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block modals %}{% endblock %}
</body>
</html>