apps/multivers/urls.py
from django.urls import re_path as url

from . import views

app_name = 'multivers'

urlpatterns = [
    url(r'^$', view=views.Index.as_view(), name='index'),
    url(r'^code(/(?P<code>[0-9]+))?$', view=views.SaveCode.as_view(), name='code'),

    url(r'^customer/(?P<pk>[0-9]+)/edit$', view=views.CustomerUpdate.as_view(), name='customer_update'),
    url(r'^location/(?P<pk>[0-9]+)/edit$', view=views.LocationUpdate.as_view(), name='location_update'),
    url(r'^settings/(?P<pk>[0-9]+)/edit$', view=views.SettingsUpdate.as_view(), name='settings_update'),

    url(r'^products$', view=views.Products.as_view(), name='products'),
    url(r'^product/add$', view=views.ProductCreate.as_view(), name='product_add'),
    url(r'^product/(?P<pk>[0-9]+)/edit$', view=views.ProductUpdate.as_view(), name='product_edit'),
    url(r'^product/(?P<pk>[0-9]+)/delete$', view=views.ProductDelete.as_view(), name='product_delete'),

    url(r'^order/(?P<pk>[0-9]+)$', view=views.ConceptOrderView.as_view(), name='order_view'),
    url(r'^order/(?P<pk>[0-9]+)/delete$', view=views.ConceptOrderDelete.as_view(), name='order_delete'),
    url(r'^order/createFromFile$', view=views.OrdersCreateFromFile.as_view(), name='orders_create_from_file'),
    url(r'^order/sendAll$', view=views.OrdersSendAllView.as_view(), name='orders_send_all'),

    url(r'^order/(?P<pk>[0-9]+)/drink/create$', view=views.ConceptOrderDrinkCreateView.as_view(), name='order_drink_create'),
    url(r'^order/drink/(?P<pk>[0-9]+)/edit$', view=views.ConceptOrderDrinkEditView.as_view(), name='order_drink_edit'),
    url(r'^order/drink/(?P<pk>[0-9]+)/delete$', view=views.ConceptOrderDrinkDeleteView.as_view(), name='order_drink_delete'),

    url(r'^order/drink/(?P<pk>[0-9]+)/line/create', view=views.ConceptOrderDrinkLineCreateView.as_view(), name='order_drink_line_create'),
    url(r'^order/drink/line/(?P<pk>[0-9]+)/edit', view=views.ConceptOrderDrinkLineEditView.as_view(), name='order_drink_line_edit'),
    url(r'^order/drink/line/(?P<pk>[0-9]+)/delete', view=views.ConceptOrderDrinkLineDeleteView.as_view(), name='order_drink_line_delete'),

    url(r'^test$', view=views.test, name='test'),
]

urls.py
from django.conf import settings
from django.urls import re_path as url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^multivers/', include('apps.multivers.urls')),
    url(r'^grolsch/', include('apps.grolsch.urls')),
    url(r'^mail/', include('apps.mail.urls')),
    url(r'^flow/', include('apps.flowguard.urls')),
    url(r'^hygiene/', include('apps.hygiene.urls')),
    url(r'^', include('apps.general.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/multivers/views.py
import json
from datetime import datetime
from urllib.parse import unquote

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, DeleteView, CreateView
from django.views.generic import UpdateView
from django.views.generic.base import RedirectView, View
from django.views.generic.detail import DetailView
from moneybird import MoneyBird, TokenAuthentication

from apps.multivers.defaults import make_orderline, make_order
from apps.multivers.forms import FileForm, ProductForm, ConceptOrderDrinkForm, ConceptOrderDrinkLineForm, SendOrdersForm
from apps.multivers.tools_multivers import Multivers, MultiversOrderLine, MultiversOrder
from apps.util.profiling import profile
from . import tools_multivers
from .models import Settings, Customer, Product, Location, ConceptOrder, ConceptOrderDrink, ConceptOrderDrinkLine


class Index(LoginRequiredMixin, ListView):
    queryset = ConceptOrder.objects.all().prefetch_related('conceptorderdrink_set')

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)

        context['send_form'] = SendOrdersForm()
        context['create_order_form'] = FileForm()

        context['new_products'] = Product.objects.filter(Q(multivers_id__isnull=True) | Q(multivers_id__exact=""))
        context['new_customers'] = Customer.objects.filter(Q(multivers_id__isnull=True) | Q(multivers_id__exact=""))
        context['new_locations'] = Location.objects.filter(no_discount__isnull=True)

        return context


class SaveCode(LoginRequiredMixin, RedirectView):
    def dispatch(self, request, *args, **kwargs):
        if 'code' in kwargs and kwargs['code']:
            Settings.set('auth_code', unquote(kwargs['code']))
        elif 'code' in request.GET and request.GET['code']:
            Settings.set('auth_code', request.GET['code'])
        return super(SaveCode, self).dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse('multivers:index')


class ConceptOrderView(LoginRequiredMixin, DetailView):
    queryset = ConceptOrder.objects.all().prefetch_related('conceptorderdrink_set',
                                                           'conceptorderdrink_set__locations',
                                                           'conceptorderdrink_set__conceptorderdrinkline_set',
                                                           'conceptorderdrink_set__conceptorderdrinkline_set__product')

    @profile
    def dispatch(self, request, *args, **kwargs):
        return super(ConceptOrderView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ConceptOrderView, self).get_context_data(**kwargs)

        context['drink_create_form'] = ConceptOrderDrinkForm()

        for drink in context['object'].conceptorderdrink_set.all():
            drink.edit_form = ConceptOrderDrinkForm(instance=drink)
            drink.line_create_form = ConceptOrderDrinkLineForm()
            drink.line_create_form.html_id = "ConceptOrderDrinkLine-" + str(drink.pk)

            for line in drink.conceptorderdrinkline_set.all():
                line.edit_form = ConceptOrderDrinkLineForm(instance=line)

        return context


class ConceptOrderDrinkCreateView(LoginRequiredMixin, CreateView):
    model = ConceptOrderDrink
    form_class = ConceptOrderDrinkForm
    
    def dispatch(self, request, *args, **kwargs):
        self.order = get_object_or_404(ConceptOrder, pk=self.kwargs['pk'])
        return super(ConceptOrderDrinkCreateView, self).dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        ctx = super(ConceptOrderDrinkCreateView, self).get_context_data(**kwargs)
        ctx['order'] = self.order
        return ctx

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.order = self.order
        self.object.save()
        return super(ConceptOrderDrinkCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('multivers:order_view', kwargs={'pk': self.object.order.pk})


class ConceptOrderDrinkEditView(LoginRequiredMixin, UpdateView):
    model = ConceptOrderDrink
    form_class = ConceptOrderDrinkForm

    def get_context_data(self, **kwargs):
        ctx = super(ConceptOrderDrinkEditView, self).get_context_data(**kwargs)
        ctx['order'] = self.object.order
        return ctx

    def get_success_url(self):
        return reverse('multivers:order_view', kwargs={'pk': self.object.order.pk})


class ConceptOrderDrinkDeleteView(LoginRequiredMixin, DeleteView):
    model = ConceptOrderDrink

    def get_success_url(self):
        return reverse('multivers:order_view', kwargs={'pk': self.object.order.pk})


class ConceptOrderDrinkLineCreateView(LoginRequiredMixin, CreateView):
    model = ConceptOrderDrinkLine
    form_class = ConceptOrderDrinkLineForm

    def dispatch(self, request, *args, **kwargs):
        self.drink = get_object_or_404(ConceptOrderDrink, pk=self.kwargs['pk'])
        return super(ConceptOrderDrinkLineCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(ConceptOrderDrinkLineCreateView, self).get_context_data(**kwargs)
        ctx['drink'] = self.drink
        return ctx

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.drink = self.drink
        self.object.save()
        return super(ConceptOrderDrinkLineCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('multivers:order_view', kwargs={'pk': self.object.drink.order.pk})


class ConceptOrderDrinkLineEditView(LoginRequiredMixin, UpdateView):
    model = ConceptOrderDrinkLine
    form_class = ConceptOrderDrinkLineForm

    def get_context_data(self, **kwargs):
        ctx = super(ConceptOrderDrinkLineEditView, self).get_context_data(**kwargs)
        ctx['drink'] = self.object.drink
        return ctx

    def get_success_url(self):
        return reverse('multivers:order_view', kwargs={'pk': self.object.drink.order.pk})


class ConceptOrderDrinkLineDeleteView(LoginRequiredMixin, DeleteView):
    model = ConceptOrderDrinkLine

    def get_success_url(self):
        return reverse('multivers:order_view', kwargs={'pk': self.object.drink.order.pk})


class OrdersCreateFromFile(LoginRequiredMixin, FormView):
    form_class = FileForm
    template_name = 'multivers/file_upload.html'
    success_url = reverse_lazy('multivers:index')

    def _create_missing_objects(self, data):
        for customer in data['drinks'].keys():
            if not Customer.objects.filter(alexia_name=customer).exists():
                customer_obj = Customer()
                customer_obj.alexia_name = customer
                customer_obj.save()

        for product_id, product_name in data['products'].items():
            product, _ = Product.objects.get_or_create(alexia_id=product_id)
            product.alexia_name = product_name
            product.save()

        alexia_locations = set()

        for drinks in data['drinks'].values():
            for drink in drinks:
                for location in drink['location']:
                    alexia_locations.add(location)

        for alexia_location in alexia_locations:
            if not Location.objects.filter(name=alexia_location).exists():
                location = Location()
                location.name = alexia_location
                location.save()

    def form_valid(self, form):
        data = form.cleaned_json

        self._create_missing_objects(data)

        for customer_name, drinks in data['drinks'].items():
            order = ConceptOrder()
            order.customer = Customer.objects.get(alexia_name=customer_name)
            order.date = datetime.now()
            order.save()

            for drink in drinks:
                order_drink = ConceptOrderDrink()
                order_drink.order = order
                order_drink.date = datetime.strptime(drink['date'], '%d-%m-%Y')
                order_drink.name = drink['drink_name']
                order_drink.save()

                for location in drink['location']:
                    order_drink.locations.add(Location.objects.get(name=location))

                for product_id, quantity in drink['products'].items():
                    order_drink_line = ConceptOrderDrinkLine()
                    order_drink_line.drink = order_drink
                    order_drink_line.product = Product.objects.get(alexia_id=product_id)
                    order_drink_line.amount = quantity
                    order_drink_line.save()

        return super(OrdersCreateFromFile, self).form_valid(form)


class OrdersSendAllView(LoginRequiredMixin, FormView):
    form_class = SendOrdersForm

    def form_valid(self, form):
        bookkeeping = Settings.get("bookkeeping_handler")
        if bookkeeping == "multivers":
            multivers, do_redirect = Multivers.instantiate_or_redirect(self.request)
            if do_redirect: return do_redirect

            admin = Settings.get('db')

            orders = ConceptOrder.objects.all()

            for order in orders:
                multivers_order = order.as_multivers(revenue_account=form.cleaned_data['override_revenue_account'])
                multivers.create_order(administration=admin, order=multivers_order)
        elif bookkeeping == "moneybird":
            moneybird = MoneyBird(TokenAuthentication(Settings.get("moneybird_token")))
            administrations = moneybird.get('administrations')
            administration = administrations[0]['id']

            orders = ConceptOrder.objects.all()

            for order in orders:

apps/multivers/templates/multivers/conceptorder_detail.html
{% extends 'base.html' %}
{% load i18n bootstrap_form %}

{% block content %}
    <h1>
        {{ object }}
        <button data-toggle="modal" data-target="#create-ConceptOrderDrink" class="btn btn-secondary btn-sm">
            + Add Drink
        </button>
    </h1>
    {% for drink in object.conceptorderdrink_set.all %}
        <h2>
            {{ drink }}
            <button data-toggle="modal" data-target="#edit-ConceptOrderDrink-{{ drink.pk }}"
                    class="btn btn-secondary btn-sm">
                <span class="oi oi-pencil"></span>
            </button>
            <button data-toggle="modal" data-target="#delete-ConceptOrderDrink-{{ drink.pk }}"
                    class="btn btn-secondary btn-sm">
                <span class="oi oi-trash"></span>
            </button>
        </h2>
        <p>
            <strong>Location</strong>: {{ drink.locations.all|join:", " }}
        </p>
        <p>
            <strong>Date</strong>: {{ drink.date|date:"d-m-Y" }}
        </p>
        <table class="table">
            <thead>
            <tr>
                <th>
                    Product
                </th>
                <th>Quantity</th>
                <th><!-- Buttons --></th>
            </tr>
            </thead>
            <tbody>
            {% for line in drink.conceptorderdrinkline_set.all %}
                <tr>
                    <td>{{ line.product }}</td>
                    <td>{{ line.amount }}</td>
                    <td>
                        <button data-toggle="modal" data-target="#edit-ConceptOrderDrinkLine-{{ line.pk }}"
                                class="btn btn-secondary btn-sm">
                            <span class="oi oi-pencil"></span>
                        </button>
                        <button data-toggle="modal" data-target="#delete-ConceptOrderDrinkLine-{{ line.pk }}"
                                class="btn btn-secondary btn-sm">
                            <span class="oi oi-trash"></span>
                        </button>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="3">
                    <button data-toggle="modal" data-target="#create-ConceptOrderDrinkLine-{{ drink.pk }}"
                            class="btn btn-secondary btn-sm">
                        + Add line
                    </button>
                </td>
            </tr>
            </tbody>
        </table>
    {% endfor %}
{% endblock %}

{% block modals %}
    {% bootstrap_create_modal drink_create_form 'multivers:order_drink_create' object.pk %}

    {% for drink in object.conceptorderdrink_set.all %}
        {% bootstrap_edit_modal drink drink.edit_form 'multivers:order_drink_edit' drink.pk %}
        {% bootstrap_delete_modal drink 'multivers:order_drink_delete' drink.pk %}

        {% bootstrap_create_modal drink.line_create_form 'multivers:order_drink_line_create' drink.pk %}

        {% for line in drink.conceptorderdrinkline_set.all %}
            {% bootstrap_edit_modal line line.edit_form 'multivers:order_drink_line_edit' line.pk %}
            {% bootstrap_delete_modal line 'multivers:order_drink_line_delete' line.pk %}
        {% endfor %}
    {% endfor %}
{% endblock %}

apps/multivers/templates/multivers/conceptorder_list.html
{% extends 'base.html' %}
{% load i18n bootstrap_form %}

{% block content %}
    {% if new_products or new_customers or new_locations %}
    <h1>Unresolved issues</h1>
    <p>
        Please resolve the following issues before sending any pending orders:
    </p>
    <ul>
    {% for product in new_products %}
        <li>
            {% url 'multivers:product_edit' product.pk as product_url %}
            {% blocktrans %}
                Please map the new product "<a href="{{ product_url }}">{{ product }}</a>" to a multivers ID and name.
            {% endblocktrans %}
        </li>
    {% endfor %}
    {% for customer in new_customers %}
        <li>
            {% url 'multivers:customer_edit' customer.pk as customer_url %}
            {% blocktrans %}
                Please map the new customer "<a href="{{ customer_url }}">{{ customer }}</a>" to a multivers ID.
            {% endblocktrans %}
        </li>
    {% endfor %}
    {% for location in new_locations %}
        <li>
            {% url 'multivers:location_update' location.pk as location_url %}
            {% blocktrans %}
                Please update the discount type of the new location "<a href="{{ location_url }}">{{ location }}</a>".
            {% endblocktrans %}
        </li>
    {% endfor %}
    </ul>
    {% endif %}

    <h1>
        Pending concept orders
    </h1>

    <p>
        {% if conceptorder_list and not new_products and not new_customers and not new_locations %}
            <button type="button" data-toggle="modal" class="btn btn-primary" data-target="#form-send">
                Send All
            </button>
        {% endif %}
        <button type="button" data-toggle="modal" class="btn btn-secondary" data-target="#create-ConceptOrder">
            + From File
        </button>
    </p>

    <table class="table">
        <thead>
        <tr>
            <th>Date</th>
            <th>Customer</th>
            <th>Drink count</th>
            <th><!-- Buttons --></th>
        </tr>
        </thead>
        <tbody>
        {% for order in conceptorder_list %}
            <tr>
                <td>{{ order.date|date:"d-m-Y" }}</td>
                <td>{{ order.customer }}</td>
                <td>{{ order.conceptorderdrink_set.all|length }}</td>
                <td>
                    <a href="{% url 'multivers:order_view' order.pk %}" class="btn btn-secondary btn-sm">View</a>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                            data-target="#delete-ConceptOrder-{{ order.pk }}">
                        <span class="oi oi-trash"></span>
                    </button>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td><emph>There are no pending concept orders right now.</emph></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block modals %}
    {% for order in conceptorder_list %}
        {% bootstrap_delete_modal order 'multivers:order_delete' order.pk %}
    {% endfor %}

    {% bootstrap_create_modal create_order_form 'multivers:orders_create_from_file' %}

    {% bootstrap_form_modal "send" "Send all pending invoices" send_form "multivers:orders_send_all" %}
{% endblock %}

apps/multivers/templates/multivers/conceptorderdrink_form.html
{% extends 'base.html' %}
{% load bootstrap_form %}

{% block content %}
    <h1>Create Order Drink</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form|bootstrap_form }}
{#        <a href="{% url 'multivers:order_view' form.instance.order.pk %}">Back</a>#}
        <input type="submit" value="Save" class="btn btn-primary">
    </form>
{% endblock %}

apps/multivers/templates/multivers/conceptorderdrinkline_form.html
{% extends 'base.html' %}
{% load i18n bootstrap_form %}

{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        {{ form|bootstrap_form }}
        <a href="{% url 'multivers:order_view' drink.order.pk %}" class="btn btn-secondary">Back</a>
        <input type="submit" class="btn btn-primary" value="Save">
    </form>
{% endblock %}

apps/multivers/templates/multivers/costumer_form.html
{% extends 'base.html' %}
{% block content %}
    <form action="#" method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    <a href="{% url 'multivers:index' %}">Back</a>
{% endblock %}

apps/multivers/templates/multivers/db.html
{% extends 'base.html' %}

{% block content %}
    {% for db in dbs %}
        <a href="{% url 'multivers:select_db' db.name %}">{{ db.name }} {{ db.value }}</a><br>
    {% endfor %}
{% endblock %}

apps/multivers/templates/multivers/file_upload.html
{% extends 'base.html' %}
{% load bootstrap_form %}
{% block content %}
    <form action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|bootstrap_form }}
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
{% endblock %}

apps/multivers/templates/multivers/location_form.html
{% extends 'base.html' %}
{% block content %}
    <form action="#" method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    <a href="{% url 'multivers:index' %}">Back</a>
{% endblock %}

apps/multivers/templates/multivers/no_oauth.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}SBZ -- No Multivers OAUTH key{% endblock %}

{% block content %}
<p>
    No OAUTH keys found, so you will have to request them by clicking the following link: <br>
<a href="{{ mv_oauth_url }}">{{ mv_oauth_url }}</a>
</p>
{% endblock %}

apps/multivers/templates/multivers/product_form.html
{% extends 'base.html' %}
{% load i18n bootstrap_form %}

{% block content %}
    <form action="#" method="post" class="form">
        {% csrf_token %}
        {{ form|bootstrap_form }}
        <a href="{% url 'multivers:products' %}" class="btn btn-secondary">Back</a>
        <input type="submit" class="btn btn-primary float-right" value="{% if object %}Update{% else %}Create{% endif %}">
    </form>
{% endblock %}

apps/multivers/templates/multivers/product_list.html
{% extends 'base.html' %}
{% load i18n bootstrap_form %}

{% block content %}
    <h1>
        Multivers/Alexia products
        <button class="btn btn-secondary" data-toggle="modal" data-target="#create-Product">
            + Create
        </button>
    </h1>

    <table class="table">
        <thead>
        <tr>
            <th colspan="2">Alexia Name</th>
            <th colspan="2">Multivers Name</th>
            <th>Margin?</th>
            <th><!-- Buttons --></th>
        </tr>
        </thead>
        <tbody>
        {% for product in product_list %}
            <tr>
                <td>{{ product.alexia_id }}</td>
                <td>{{ product.alexia_name }}</td>
                <td>{{ product.multivers_id }}</td>
                <td>{{ product.multivers_name }}</td>
                <td>
                    {% if product.margin %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </td>
                <td>
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                            data-target="#edit-Product-{{ product.pk }}">
                        <span class="oi oi-pencil"></span>
                    </button>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                            data-target="#delete-Product-{{ product.pk }}">
                        <span class="oi oi-trash"></span>
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block modals %}
    {% bootstrap_create_modal create_form 'multivers:product_add' %}

    {% for product in product_list %}
        {% bootstrap_edit_modal product product.edit_form 'multivers:product_edit' product.pk %}
        {% bootstrap_delete_modal product 'multivers:product_delete' product.pk %}
    {% endfor %}
{% endblock %}

apps/multivers/templates/multivers/send.html
{% extends 'base.html' %}
{% block content %}
    <table>
    <tr><th>Customer</th><th>Order id</th><th>Total order amount</th></tr>
        {% for line in result %}
            <tr>
                <td>{{ line.0 }}</td>
                <td>{{ line.1 }}</td>
                <td>{{ line.2 }}</td>
            </tr>
        {% endfor %}
    </table>
    <a href="{% url 'multivers:clear_cache' %}">Upload new file</a><br>
{% endblock %}

apps/multivers/templates/multivers/settings_form.html
{% extends 'base.html' %}
{% block content %}
    <form action="#" method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    <a href="{% url 'multivers:index' %}">Back</a>
{% endblock %}